"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let month = "jan";
console.log(month == "Ramdan");
let monthNew = "Muharram";
console.log(month != "Ramdan");
let age = 22;
console.log(age < 18);
let ageNew = 12;
console.log(ageNew < 18);
let ageOne = 19;
console.log(ageOne >= 18);
let ageTwo = 18;
console.log(ageTwo > 18, "university");
console.log(ageTwo < 18, "school");
