"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'corolla';
console.log("Is car =='corolla'?  I predict true.");
console.log(car == 'corolla');
console.log("Is car =='cultus'?  I predict false.");
console.log(car == 'cultus');
let staphylococcus = 'present';
console.log("Is staphylococcus == 'present'? I predict true.");
console.log(staphylococcus == 'present');
console.log("Is staphylococcus == 'absent'? I predict false.");
console.log(staphylococcus == 'absent');
let listeriaCatalaseTest = 'positive';
console.log("Is listeriaCatalaseTest == 'positive'? I predict true.");
console.log(listeriaCatalaseTest == 'positive');
console.log("Is listeriaCatalaseTest == 'negative'? I predict false.");
console.log(listeriaCatalaseTest == 'negative');
let pneumococci = 'gram +ve';
console.log("Is pneumococci == 'gram +ve'? I predict true.");
console.log(pneumococci == 'gram +ve');
console.log("Is pneumococci == 'gram -ve'? I predict false.");
console.log(pneumococci == 'gram -ve');
let fungi = 'aspergillus';
console.log("Is fungi == 'aspergillus? I predict true.");
console.log(fungi == 'aspergillus');
console.log("Is fungi == 'nocardia'? I predict false.");
console.log(fungi == 'nocardia');
